# node 10.16 is LTS @ September-2019
image: node:10.16-stretch

tags: 
    - widgetlab

# To be cached between jobs
#cache:
#  paths:
#    - node_modules/

stages:
    - install
#    - build

npm_install:
  stage: install
  tags: widgetlab
  script:
    - npm install

#npm_build:
#  stage: build
#  tags: widgetlab
#  script:
#    - npm run build
