# node 10.16 is LTS @ September-2019
image: node:10.16-stretch

stages:
    - prepare
    - build

# install node_modules to prepare build

npm_install:
  stage: prepare
  tags: 
    - widgetlab
  artifacts:
    paths:
      - package-lock.json
  script:
    - ls node_modules
    - npm install

# build widget

npm_build:
  stage: build
  tags: 
    - widgetlab
  script:
    - npm run build
