# GitLab CI/CD configuration
# P13@3DS.com
# please read Gitlab-CI-Setup.md to enable CI/CD on the repository

# node 10.16 is LTS @ September-2019
image: node:10.16-stretch

stages:
    - prepare
    - build
    - deploy

##########################
# npm install
# stage: prepare 
# install node_modules to prepare build

npm_install:
  stage: prepare
  tags: 
    - widgetlab
  artifacts:
    expire_in: 10min
    untracked: true
  script:
    - npm install

##########################
# npm build
# stage: build
# build widget (npm run build)

npm_build:
  stage: build
  tags: 
    - widgetlab
  artifacts:
    expire_in: 10min
    paths:
      - dist/
  script:
    - npm run build

##########################
# zip_widget (master only) 
# stage: deploy
# Zip widget (dist/ content) and push it in artifacts

zip_widget:
  stage: deploy
  tags: 
    - widgetlab
  only:
    - branches
  artifacts:
    paths:
      - widget.zip
  script:
    - cd dist
    # this is NODE.js way 
    - npm install -g bestzip
    - bestzip ../widget.zip * 
    # This was old Debian way (for node:stretch image)
    #- apt-get update && apt-get install -y --no-install-recommends zip
    #- zip ../widget.zip * 
    
##########################
# push_widget (master only) 
# stage: deploy
# Push widget to AWS S3 

push_widget:
  stage: deploy
  tags: 
    - widgetlab
  only:
    - branches
  script:
    - cd dist
    - please_fail
#(TODO)

