# node 10.16 is LTS @ September-2019
image: node:10.16-stretch

# to be persisted between stages
artifacts:
  paths:
    - node_modules/
    - package-lock.json

stages:
    - install
    - build

npm_install:
  stage: install
  tags: 
    - widgetlab
  script:
    - ls node_modules
    - npm install

npm_build:
  stage: build
  tags: 
    - widgetlab
  script:
    - npm run build
